//======================================================================
// CookingCommandBehaviour.cs
// ï¿½ï¿½ï¿½ï¿½ï¿½Rï¿½}ï¿½ï¿½ï¿½hï¿½ï¿½UIï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½MonoBehaviour
// ï¿½eï¿½Rï¿½}ï¿½ï¿½ï¿½hï¿½ÌŞ—ï¿½ï¿½Eï¿½Aï¿½Nï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Ìƒeï¿½Lï¿½Xï¿½gï¿½Æƒ{ï¿½^ï¿½ï¿½ï¿½Ì”zï¿½uï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ç—ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½
//======================================================================

using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

#if UNITY_EDITOR
using UnityEditor;
#endif

public class CookingCommandBehaviour : MonoBehaviour
{
    enum SpriteSizeOption
    {
        NonKeepAspect, // ï¿½Aï¿½Xï¿½yï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½Ûï¿½ï¿½ï¿½ï¿½È‚ï¿½
        KeepAspectWithCurrentWidth, // ï¿½ï¿½ï¿½İ‚Ì•ï¿½ï¿½ï¿½ï¿½Ûï¿½ï¿½ï¿½ï¿½ÄƒAï¿½Xï¿½yï¿½Nï¿½gï¿½ï¿½ğ’²ï¿½
        KeepAspectWithCurrentHeight, // ï¿½ï¿½ï¿½İ‚Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ûï¿½ï¿½ï¿½ï¿½ÄƒAï¿½Xï¿½yï¿½Nï¿½gï¿½ï¿½ğ’²ï¿½
    }
    public class SelectCommandEvent : UnityEvent<int, int> { }

    [Header("ï¿½ï¿½ï¿½ï¿½ï¿½ÉHï¿½ŞEï¿½ï¿½ï¿½ï¿½ï¿½@ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½UIï¿½ï¿½D&D")]
    [SerializeField] private GameObject commandUIPrefab; // UIï¿½vï¿½ï¿½ï¿½nï¿½uï¿½ï¿½oï¿½^
    [SerializeField] private GameObject commandCanvas; // Canvasï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½oï¿½^
    [SerializeField] private GameObject commandUIParent; // UIï¿½Ìeï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½oï¿½^
    [SerializeField] private string materialUIPrefabName = "MaterialUI"; // ï¿½Hï¿½ï¿½UIï¿½Ì–ï¿½ï¿½O
    [SerializeField] private string actionUIPrefabName = "ActionUI"; // ï¿½ï¿½ï¿½ï¿½ï¿½@UIï¿½Ì–ï¿½ï¿½O
    [SerializeField] private bool commandCanvasStartActive = false; // ï¿½Qï¿½[ï¿½ï¿½ï¿½Jï¿½nï¿½ï¿½ï¿½ÉƒRï¿½}ï¿½ï¿½ï¿½hUIï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½é‚©

    [Header("ï¿½ï¿½ï¿½Xï¿½gï¿½Ì”zï¿½u")]
    [SerializeField] private int commandCount = 3; // ï¿½Rï¿½}ï¿½ï¿½ï¿½hï¿½Ìï¿½
    [SerializeField] private Vector2 commandPosition;           // ï¿½Rï¿½}ï¿½ï¿½ï¿½hï¿½ÌŠî€ï¿½Ê’u
    [SerializeField] private Vector2 commandDelta;              // ï¿½Rï¿½}ï¿½ï¿½ï¿½hï¿½ï¿½ï¿½Æ‚ÌƒIï¿½tï¿½Zï¿½bï¿½g
    [SerializeField] private Vector2 commandTextPosition;       // ï¿½eï¿½Lï¿½Xï¿½gï¿½ÌˆÊ’u
    [SerializeField] private Vector2 commandLeftButtonPosition; // ï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½ÌˆÊ’u
    [SerializeField] private Vector2 commandRightButtonPosition;// ï¿½Eï¿½{ï¿½^ï¿½ï¿½ï¿½ÌˆÊ’u
    [Header("ï¿½tï¿½Hï¿½ï¿½ï¿½gï¿½ğ‘€ï¿½")]
    [SerializeField] private TMP_FontAsset fontAsset;          // ï¿½gï¿½pï¿½ï¿½ï¿½ï¿½tï¿½Hï¿½ï¿½ï¿½gï¿½Aï¿½Zï¿½bï¿½g
    [SerializeField] private Color fontColor = Color.white; // ï¿½tï¿½Hï¿½ï¿½ï¿½gï¿½Jï¿½ï¿½ï¿½[
    [SerializeField] private float fontSize = 16f;              // ï¿½tï¿½Hï¿½ï¿½ï¿½gï¿½Tï¿½Cï¿½Y
    [SerializeField] private Vector2 textSize = new Vector2(200, 30); // ï¿½eï¿½Lï¿½Xï¿½gï¿½Tï¿½Cï¿½Y
    [Header("ï¿½{ï¿½^ï¿½ï¿½ï¿½ğ‘€ï¿½")]
    [SerializeField] private Sprite leftButtonSprite;  // ï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½ÌƒXï¿½vï¿½ï¿½ï¿½Cï¿½g
    [SerializeField] private Sprite rightButtonSprite; // ï¿½Eï¿½{ï¿½^ï¿½ï¿½ï¿½ÌƒXï¿½vï¿½ï¿½ï¿½Cï¿½g
    [SerializeField] private Vector2 ButtonSize = new Vector2(100, 100); // ï¿½{ï¿½^ï¿½ï¿½ï¿½Tï¿½Cï¿½Y
    [SerializeField] private SpriteSizeOption buttonSizeOption = SpriteSizeOption.NonKeepAspect; // ï¿½{ï¿½^ï¿½ï¿½ï¿½Tï¿½Cï¿½Yï¿½Iï¿½vï¿½Vï¿½ï¿½ï¿½ï¿½

    // UIï¿½vï¿½fï¿½ÌQï¿½ï¿½
    private RectTransform[] materialUIRects;
    private TextMeshProUGUI[] materialUITexts;
    private Button[] materialLeftButtons;
    private Button[] materialRightButtons;
    private RectTransform[] actionUIRects;
    private TextMeshProUGUI[] actionUITexts;
    private Button[] actionLeftButtons;
    private Button[] actionRightButtons;

    private UnityEvent checkAllSettings = new();
    private SelectCommandEvent previousMaterialEvent = new();
    private SelectCommandEvent nextMaterialEvent = new();
    private SelectCommandEvent previousActionEvent = new();
    private SelectCommandEvent nextActionEvent = new();
    private UnityEvent submitCommandEvent = new();

    private int currentChobinUIIndex;

    public int CommandCount => commandCount; // ï¿½Rï¿½}ï¿½ï¿½ï¿½hï¿½Ìï¿½
    public int CurrentChobinUIIndex => currentChobinUIIndex;

    public UnityEvent CheckAllSettings => checkAllSettings;
    public SelectCommandEvent PreviousMaterialEvent => previousMaterialEvent;
    public SelectCommandEvent NextMaterialEvent => nextMaterialEvent;
    public SelectCommandEvent PreviousActionEvent => previousActionEvent;
    public SelectCommandEvent NextActionEvent => nextActionEvent;
    public UnityEvent SubmitCommandEvent => submitCommandEvent;

    // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    void Start()
    {
        currentChobinUIIndex = 0;
        if (commandCanvasStartActive) commandCanvas.SetActive(false);
    }

    // ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½ÌXï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½iï¿½ï¿½ï¿½gï¿½pï¿½j
    void Update()
    {

    }

    /// <summary>
    /// ï¿½İ’ï¿½ÌŠmï¿½Fï¿½ï¿½UIï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    public bool CheckSettings()
    {
        bool commandUIisCorrect = true;

        // UIï¿½Ìï¿½ï¿½ğ’²ï¿½
        if (commandCount < 1)
        {
            commandCount = 1;
        }
        // ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½Wï¿½ğ’²ï¿½
        if (commandLeftButtonPosition.x >= 0)
        {
            commandLeftButtonPosition.x = -1e-5f; // ï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½ÌˆÊ’uï¿½ï¿½ï¿½Eï¿½ï¿½ï¿½É—ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
            Debug.LogWarning("ï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½ÌˆÊ’uï¿½ï¿½ï¿½Eï¿½ï¿½ï¿½Éİ’è‚³ï¿½ï¿½Ä‚ï¿½ï¿½Ü‚ï¿½ï¿½Bï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½Íï¿½ï¿½ï¿½ï¿½É”zï¿½uï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½B");
        }
        if (commandRightButtonPosition.x <= 0)
        {
            commandRightButtonPosition.x = 1e-5f; // ï¿½Eï¿½{ï¿½^ï¿½ï¿½ï¿½ÌˆÊ’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½É—ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
            Debug.LogWarning("ï¿½Eï¿½{ï¿½^ï¿½ï¿½ï¿½ÌˆÊ’uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Éİ’è‚³ï¿½ï¿½Ä‚ï¿½ï¿½Ü‚ï¿½ï¿½Bï¿½Eï¿½{ï¿½^ï¿½ï¿½ï¿½Í‰Eï¿½ï¿½ï¿½É”zï¿½uï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½B");
        }

        if (commandCanvas == null)
        {
            commandUIisCorrect = false;
            Debug.LogError("ï¿½wï¿½ï¿½UICanvasï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½İ’è‚³ï¿½ï¿½Ä‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½B");
        }

        if (commandUIParent == null)
        {
            commandUIisCorrect = false;
            Debug.LogError("ï¿½Rï¿½}ï¿½ï¿½ï¿½hUIï¿½Ìeï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½İ’è‚³ï¿½ï¿½Ä‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½B");
        }

        // ï¿½Hï¿½ŞEï¿½ï¿½ï¿½ï¿½ï¿½@ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½nullï¿½Å‚È‚ï¿½ï¿½ï¿½ï¿½mï¿½F
        if (commandUIPrefab != null)
        {
            bool hasText = false;
            bool hasLeftButton = false;
            bool hasRightButton = false;
            // ï¿½Hï¿½ŞƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Ìqï¿½vï¿½fï¿½ï¿½ï¿½`ï¿½Fï¿½bï¿½N
            foreach (Transform child in commandUIPrefab.transform)
            {
                if (child.GetComponent<RectTransform>())
                {
                    if (child.GetComponent<TextMeshProUGUI>())
                    {
                        hasText = true;
                    }
                    if (child.GetComponent<Button>())
                    {
                        RectTransform buttonRect = child.GetComponent<RectTransform>();
                        if (buttonRect.anchoredPosition.x < 0)
                        {
                            hasLeftButton = true;
                        }
                        else
                        {
                            hasRightButton = true;
                        }
                    }
                }
            }
            // ï¿½Kï¿½vï¿½ï¿½UIï¿½vï¿½fï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½ï¿½ï¿½ï¿½
            if (hasText && hasLeftButton && hasRightButton)
            {
            }
            else
            {
                commandUIisCorrect = false;
                if (!hasText)
                {
                    Debug.LogError("ï¿½Rï¿½}ï¿½ï¿½ï¿½hUIï¿½vï¿½ï¿½ï¿½nï¿½uï¿½ï¿½TextMeshProUGUIï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½B");
                }
                if (!hasLeftButton)
                {
                    Debug.LogError("ï¿½Rï¿½}ï¿½ï¿½ï¿½hUIï¿½vï¿½ï¿½ï¿½nï¿½uï¿½Éï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½Buttonï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½B");
                }
                if (!hasRightButton)
                {
                    Debug.LogError("ï¿½Rï¿½}ï¿½ï¿½ï¿½hUIï¿½vï¿½ï¿½ï¿½nï¿½uï¿½É‰Eï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½Buttonï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½Â‚ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½B");
                }
            }
        }
        else
        {
            commandUIisCorrect = false;
            Debug.LogError("ï¿½Rï¿½}ï¿½ï¿½ï¿½hUIï¿½vï¿½ï¿½ï¿½nï¿½uï¿½ï¿½ï¿½İ’è‚³ï¿½ï¿½Ä‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½B");
        }

        return commandUIisCorrect;
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    /// </summary>
    public void Init()
    {
        commandCanvas.SetActive(commandCanvasStartActive);
#if UNITY_EDITOR
        if (EditorApplication.isPlaying)
        {
            InitUIParent();
        }
        else
        {
            bool changeCommandCount = (commandUIParent.transform.childCount != commandCount * 2);
            bool changeMaterialUIName = (commandUIParent.transform.GetChild(0).name != materialUIPrefabName + "_0");
            bool changeActionUIName = (commandUIParent.transform.GetChild(1).name != actionUIPrefabName + "_0");
            if (changeCommandCount || changeMaterialUIName || changeActionUIName)
            {
                Debug.Log("ï¿½Rï¿½}ï¿½ï¿½ï¿½hï¿½ï¿½ï¿½ï¿½ï¿½ÏXï¿½ï¿½ï¿½ê‚½ï¿½ï¿½ï¿½ßAUIï¿½ï¿½ï¿½Äï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½B");
                EditorApplication.delayCall += InitUIParent; // UIï¿½Ìeï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            }
            else
            {
                InitUI(); // UIï¿½ÌƒXï¿½^ï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½V
            }
        }
#else
        InitUIParent();
#endif

        Debug.Log("CookingCommandBehaviourï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÉŠï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½ï¿½B");
    }

    private void InitUIParent()
    {
        materialUIRects = new RectTransform[commandCount];
        actionUIRects = new RectTransform[commandCount];
        materialUITexts = new TextMeshProUGUI[commandCount];
        materialLeftButtons = new Button[commandCount];
        materialRightButtons = new Button[commandCount];
        actionUITexts = new TextMeshProUGUI[commandCount];
        actionLeftButtons = new Button[commandCount];
        actionRightButtons = new Button[commandCount];

        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½UIï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½íœ
        while (commandUIParent.transform.childCount > 0)
        {
            DestroyImmediate(commandUIParent.transform.GetChild(0).gameObject);
        }

        for (int i = 0; i < commandCount; i++)
        {
            GameObject materialUIObject = null;
            GameObject actionUIObject = null;
#if UNITY_EDITOR
            materialUIObject = UnityEditor.PrefabUtility.InstantiatePrefab(commandUIPrefab, commandUIParent.transform) as GameObject;
            actionUIObject = UnityEditor.PrefabUtility.InstantiatePrefab(commandUIPrefab, commandUIParent.transform) as GameObject;
#else
            materialUIObject = Instantiate(commandUIPrefab, commandUIParent.transform);
            actionUIObject = Instantiate(commandUIPrefab, commandUIParent.transform);
#endif
            materialUIObject.name = materialUIPrefabName + "_" + i; // ï¿½Hï¿½ï¿½UIï¿½Ì–ï¿½ï¿½Oï¿½ï¿½İ’ï¿½
            actionUIObject.name = actionUIPrefabName + "_" + i; // ï¿½ï¿½ï¿½ï¿½ï¿½@UIï¿½Ì–ï¿½ï¿½Oï¿½ï¿½İ’ï¿½

            // UIï¿½ÌˆÊ’uï¿½ï¿½İ’ï¿½
            materialUIRects[i] = materialUIObject.GetComponent<RectTransform>();
            actionUIRects[i] = actionUIObject.GetComponent<RectTransform>();

            foreach (Transform t in materialUIObject.transform)
            {
                if (t.TryGetComponent<RectTransform>(out var rectTransform))
                {
                    if (t.GetComponent<TextMeshProUGUI>() != null)
                    {
                        materialUITexts[i] = t.GetComponent<TextMeshProUGUI>();
                    }
                    else if (t.GetComponent<Button>() != null)
                    {
                        if (rectTransform.anchoredPosition.x < 0)
                        {
                            materialLeftButtons[i] = t.GetComponent<Button>();
                        }
                        else
                        {
                            materialRightButtons[i] = t.GetComponent<Button>();
                        }
                    }
                }
            }
            foreach (Transform t in actionUIObject.transform)
            {
                if (t.TryGetComponent<RectTransform>(out var rectTransform))
                {
                    if (t.GetComponent<TextMeshProUGUI>() != null)
                    {
                        actionUITexts[i] = t.GetComponent<TextMeshProUGUI>();
                    }
                    else if (t.GetComponent<Button>() != null)
                    {
                        if (rectTransform.anchoredPosition.x < 0)
                        {
                            actionLeftButtons[i] = t.GetComponent<Button>();
                        }
                        else
                        {
                            actionRightButtons[i] = t.GetComponent<Button>();
                        }
                    }
                }
            }
        }
        InitUI();
#if UNITY_EDITOR
        if (!EditorApplication.isPlaying)
        {
            EditorApplication.delayCall -= InitUIParent; // ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½ï¿½é‚½ï¿½ß‚É‰ï¿½ï¿½ï¿½
        }
#endif
    }

    private void InitUI()
    {
        //ï¿½{ï¿½^ï¿½ï¿½ï¿½ÌƒTï¿½Cï¿½Yï¿½Iï¿½vï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½É‰ï¿½ï¿½ï¿½ï¿½ÄƒTï¿½Cï¿½Yï¿½ğ’²ï¿½
        ButtonSize = SpriteSize(leftButtonSprite, ButtonSize, buttonSizeOption);
#if UNITY_EDITOR
        bool recallInitUIParent = false;
        if (materialUIRects == null)
        {
            recallInitUIParent = true;
        }
        else if (materialUIRects.Length != commandCount)
        {
            recallInitUIParent = true;
        }
        if (recallInitUIParent)
        {
            Debug.LogWarning("UIï¿½vï¿½fï¿½Ì”zï¿½ñ‚ªï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½ï¿½ï¿½Aï¿½Rï¿½}ï¿½ï¿½ï¿½hï¿½ï¿½ï¿½Æˆï¿½vï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½BUIï¿½Ìeï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½Äï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½B");
            EditorApplication.delayCall += InitUIParent; // UIï¿½Ìeï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            return;
        }
#endif

        // UIï¿½Ì”zï¿½uï¿½ÆƒXï¿½^ï¿½Cï¿½ï¿½ï¿½ï¿½İ’ï¿½
        for (int i = 0; i < commandCount; i++)
        {
            materialUIRects[i].anchoredPosition = commandPosition + new Vector2(0, -commandDelta.y * i);
            actionUIRects[i].anchoredPosition = commandPosition + new Vector2(commandDelta.x, -commandDelta.y * i);

            TextMeshProUGUI materialUIText = materialUITexts[i];
            Button materialLeftButton = materialLeftButtons[i];
            Button materialRightButton = materialRightButtons[i];
            TextMeshProUGUI actionUIText = actionUITexts[i];
            Button actionLeftButton = actionLeftButtons[i];
            Button actionRightButton = actionRightButtons[i];

            // ï¿½eï¿½Lï¿½Xï¿½gï¿½ÌƒXï¿½^ï¿½Cï¿½ï¿½ï¿½ï¿½İ’ï¿½
            materialUIText.rectTransform.anchoredPosition = commandTextPosition;
            materialUIText.rectTransform.sizeDelta = textSize;
            materialUIText.font = fontAsset;
            materialUIText.color = fontColor;
            materialUIText.fontSize = fontSize;
            actionUIText.rectTransform.anchoredPosition = commandTextPosition;
            actionUIText.rectTransform.sizeDelta = textSize;
            actionUIText.font = fontAsset;
            actionUIText.color = fontColor;
            actionUIText.fontSize = fontSize;

            // ï¿½{ï¿½^ï¿½ï¿½ï¿½ÌƒXï¿½^ï¿½Cï¿½ï¿½ï¿½ï¿½İ’ï¿½
            materialLeftButton.GetComponent<RectTransform>().anchoredPosition = commandLeftButtonPosition;
            materialLeftButton.GetComponent<RectTransform>().sizeDelta = ButtonSize;
            Image materialLeftButtonImage = materialLeftButton.GetComponent<Image>();
            if (materialLeftButtonImage != null && leftButtonSprite != null)
            {
                materialLeftButtonImage.sprite = leftButtonSprite;
            }
            materialRightButton.GetComponent<RectTransform>().anchoredPosition = commandRightButtonPosition;
            materialRightButton.GetComponent<RectTransform>().sizeDelta = ButtonSize;
            Image materialRightButtonImage = materialRightButton.GetComponent<Image>();
            if (materialRightButtonImage != null && rightButtonSprite != null)
            {
                materialRightButtonImage.sprite = rightButtonSprite;
            }
            actionLeftButton.GetComponent<RectTransform>().anchoredPosition = commandLeftButtonPosition;
            actionLeftButton.GetComponent<RectTransform>().sizeDelta = ButtonSize;
            Image actionLeftButtonImage = actionLeftButton.GetComponent<Image>();
            if (actionLeftButtonImage != null && leftButtonSprite != null)
            {
                actionLeftButtonImage.sprite = leftButtonSprite;
            }
            actionRightButton.GetComponent<RectTransform>().anchoredPosition = commandRightButtonPosition;
            actionRightButton.GetComponent<RectTransform>().sizeDelta = ButtonSize;
            Image actionRightButtonImage = actionRightButton.GetComponent<Image>();
            if (actionRightButtonImage != null && rightButtonSprite != null)
            {
                actionRightButtonImage.sprite = rightButtonSprite;
            }

            // ï¿½{ï¿½^ï¿½ï¿½ï¿½ÌƒNï¿½ï¿½ï¿½bï¿½Nï¿½Cï¿½xï¿½ï¿½ï¿½gï¿½ï¿½İ’ï¿½
            int commandIndex = i; // ï¿½ï¿½ï¿½[ï¿½Jï¿½ï¿½ï¿½Ïï¿½ï¿½ï¿½ï¿½gï¿½pï¿½ï¿½ï¿½ÄƒNï¿½ï¿½ï¿½[ï¿½Wï¿½ï¿½ï¿½[ï¿½Ì–ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            materialLeftButton.onClick.RemoveAllListeners();
            materialRightButton.onClick.RemoveAllListeners();
            actionLeftButton.onClick.RemoveAllListeners();
            actionRightButton.onClick.RemoveAllListeners();

            materialLeftButton.onClick.AddListener(() => previousMaterialEvent.Invoke(currentChobinUIIndex, commandIndex));
            materialRightButton.onClick.AddListener(() => nextMaterialEvent.Invoke(currentChobinUIIndex, commandIndex));
            actionLeftButton.onClick.AddListener(() => previousActionEvent.Invoke(currentChobinUIIndex, commandIndex));
            actionRightButton.onClick.AddListener(() => nextActionEvent.Invoke(currentChobinUIIndex, commandIndex));
        }
    }

    public void UpdateMaterialText(int commandIndex, string name)
    {
        if (materialUITexts == null)
        {
            return;
        }
        else if (commandIndex < 0 || commandIndex >= materialUITexts.Length)
        {
            return;
        }
        materialUITexts[commandIndex].text = name;
    }

    public void UpdateActionText(int commandIndex, string name)
    {
        if (actionUITexts == null)
        {
            return;
        }
        else if (commandIndex < 0 || commandIndex >= actionUITexts.Length)
        {
            return;
        }
        actionUITexts[commandIndex].text = name;
    }

    private Vector2 SpriteSize(Sprite sprite, Vector2 targetSize, SpriteSizeOption spriteSizeOption)
    {
        Vector2 newSize = targetSize;
        switch (spriteSizeOption)
        {
            case SpriteSizeOption.NonKeepAspect:
                // ï¿½ï¿½ï¿½Ì‚Ü‚ï¿½
                break;
            case SpriteSizeOption.KeepAspectWithCurrentWidth:
                if (sprite != null)
                {
                    float aspectRatio = sprite.rect.height / sprite.rect.width;
                    newSize.y = newSize.x * aspectRatio;
                }
                break;
            case SpriteSizeOption.KeepAspectWithCurrentHeight:
                if (sprite != null)
                {
                    float aspectRatio = sprite.rect.width / sprite.rect.height;
                    newSize.x = newSize.y * aspectRatio;
                }
                break;
        }
        return newSize;
    }

    public void ShowCommand(int chobinIndex)
    {
        commandCanvas.SetActive(true);
        currentChobinUIIndex = chobinIndex;
    }

    public void SubmitCommand()
    {
        submitCommandEvent.Invoke();
        commandCanvas.SetActive(false);
    }

    public string GetMaterialName(int index)
    {
        if (materialUITexts != null && index >= 0 && index < materialUITexts.Length)
            return materialUITexts[index].text;
        return "";
    }

    public float GetCookTime()
    {
        // ãƒ‡ãƒ¢ç”¨: å®Ÿéš›ã«ã¯UIã®å€¤ã‚„å¤‰æ•°ã‚’å–å¾—
        return 40f;
    }

    public int GetSelectedSteps()
    {
        // ãƒ‡ãƒ¢ç”¨: å®Ÿéš›ã«ã¯UIã®å€¤ã‚„å¤‰æ•°ã‚’å–å¾—
        return 3;
    }

#if UNITY_EDITOR
    private void OnValidate()
    {
        checkAllSettings.Invoke();
    }
#endif
}